modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
license="MIT License"
issueTrackerURL="https://github.com/Rahala/LottaTerracotta/issues" #optional

[[mods]]
modId="lottaterracotta"
version="1.16.4-1.3.1"
displayName="Lotta Terracotta"
authors="Rahala" #optional
description='''
Terracotta da vida baby
'''

[[dependencies.lottaterracotta]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
