modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
license="MIT License"
issueTrackerURL="https://github.com/Rahala/LottaTerracotta/issues" #optional

[[mods]]
modId="lottaterracotta"
version="1.18.2-1.4.1"
displayName="Lotta Terracotta"
authors="Rahala" #optional
description='''
Terracotta da vida baby
'''

[[dependencies.lottaterracotta]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lottaterracotta]]
modId = "forge"
mandatory = true
versionRange = "[40.0.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lottaterracotta]]
modId = "blueprint"
mandatory = true
versionRange = "[5.2.1,)"
ordering = "BEFORE"
side = "BOTH"